services:
  broker:
    container_name: registry-broker
    image: "bitnami/rabbitmq:3.13.3"
    network_mode: "host"
    # ports:
    #   - "1883:1883" # MQTT port
    #   - "5672:5672" # AMQP port
    #   - "15672:15672" # Web UI
    environment:
      # full list of env variables available at https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/README.md
      RABBITMQ_PLUGINS: "rabbitmq_management rabbitmq_mqtt"
      RABBITMQ_USERNAME: "intersect_username"
      RABBITMQ_PASSWORD: "intersect_password"
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: "yes"
    healthcheck:
      test: rabbitmq-diagnostics -q ping && rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    # networks:
    #   - intersect_registry_network
  database:
    container_name: registry-database
    image: "bitnami/postgresql:17"
    # full list of environment variables available at https://github.com/bitnami/containers/tree/231cb510c9f39dc7100d2a0c117beaef007f5fac/bitnami/postgresql#environment-variables
    environment:
      POSTGRESQL_USERNAME: "registry_username"
      POSTGRESQL_PASSWORD: "registry_password"
      POSTGRESQL_DATABASE: "registry"
    healthcheck:
      test: pg_isready -U $POSTGRESQL_USERNAME -d $POSTGRESQL_DATABASE
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s
    network_mode: "host"
    # ports:
    #   - 5432:5432
    volumes:
      - 'intersect_registry_postgresql_data:/bitnami/postgresql'
    # networks:
    #   - intersect_registry_network

  keycloak:
    build:
      context: ./keycloak/
    container_name: keycloak
    # restart: unless-stopped
    # ports:
    #   - "8081:8080"
    network_mode: "host"
    environment:
      # FEDERATE_LDAP: "true"
      # LDAP_URL: YOUR_LDAP_URL
      # USERSDN: YOUR_USER_DN
      GOOGLE_IDP: "true"
      GOOGLE_CLIENT_ID: YOUR_CLIENT_ID
      GOOGLE_SECRET: YOUR_GOOGLE_CLIENT_SECRET
      KC_DB: postgres
      # KC_DB_URL: jdbc:postgresql://registry-database:5432/registry
      KC_DB_URL: jdbc:postgresql://localhost:5432/registry
      KC_DB_PASSWORD: registry_password
      KC_DB_USERNAME: registry_username
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      HOSTNAME: localhost
      # HTTPS: true
    depends_on:
      - database
    # networks:
    #   - intersect_registry_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  intersect_registry_network:
    driver: bridge

volumes:
  intersect_registry_postgresql_data:
    driver: local
