{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "registry-service.fullname" . }}
  labels:
    {{- include "registry-service.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if or (and .Values.ingress.tls .Values.ingress.hostname) .Values.ingress.extraTls }}
  tls:
    {{- if and .Values.ingress.tls .Values.ingress.hostname }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      {{- if .Values.ingress.secrets }}
      secretName: {{ (index .Values.ingress.secrets 0).name | quote }}
      {{- end }}
    {{- end }}
    {{- with .Values.ingress.extraTls }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "registry-service.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          {{- with .Values.ingress.extraPaths }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- end }}
    {{- with .Values.ingress.extraHosts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.ingress.extraRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
